apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  type: NodePort
  ports:
  - name: "nginx-port"
    protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30080
  selector:
    run: my-nginx